## Server (Master node)
server_ip: 192.168.56.200
cpus_server_node: 2
memory_server_node: 4096
web_interface_port: 9000
server_as_host: no # 'yes' will use/deploy number_of_hosts-1 additional hosts since the server itself will be a host (worker)

## Hosts (Worker nodes)
number_of_hosts: 2 # 1
cpus_per_host: 4
memory_per_host: 4096
energy_per_host: 200
# Disk config (only relevant if disk_capabilities is set to "yes")
hdd_disks_per_host: 1
hdd_disks_path_list: $HOME/hdd
ssd_disks_per_host: 1
ssd_disks_path_list: $HOME/ssd
create_lvm: no # "yes" to create a LVM using the previous disks. Such disks should be indicated using their /dev path
lvm_path: $HOME/lvm