namenode:
  cpu:
    max: 100
    min: 100
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  mem:
    max: 1024
    min: 1024
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  disk_read:
    min: 10
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  disk_write:
    min: 10
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
datanode:
  cpu:
    max: 300
    min: 100
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  mem:
    max: 3096
    min: 1024
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  disk_read:
    min: 10
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
  disk_write:
    min: 10
    weight: default
    boundary: 5
    boundary_type: percentage_of_max
