
- name: Initializing State Database - container limits on Node Scaler
  shell: "python3 scripts/stateDatabase/init_host_node_rescaler_v3.py {{ nodes | join(',') }} {{ containers_info | replace(' ','') | quote }} {{ resources | quote }}"
  args:
    executable: /bin/bash
