
# Starting Node Rescaler
- block:
  - name: Verify gunicorn3 installation
    command: "which gunicorn3"
    register: gunicorn3_check
    ignore_errors: true

  - name: Verify gunicorn installation
    command: "which gunicorn"
    register: gunicorn_check
    ignore_errors: true

  - name: Set gunicorn command alias
    set_fact:
      gunicorn_command_alias: "{%- if gunicorn3_check.rc == 0 -%}gunicorn3
                            {%- elif gunicorn_check.rc == 0 -%}gunicorn
                            {%- else -%}$HOME/.local/bin/gunicorn
                            {%- endif -%}"

  - name: Copy Node Scaler start script
    template:
      src: "templates/node_scaler_start.sh"
      dest: "{{ serverless_containers_path }}/scripts/services/node_scaler/start.sh"

  - import_tasks: tasks/utils/get_tmux_sessions.yml

  - name: Starting Services - Node Scaler
    shell: bash scripts/services/node_scaler/start_tmux.sh
    when: "'node_scaler' not in tmux_sessions"
    args:
      chdir: "{{ serverless_containers_path }}"
      executable: /bin/bash
  tags: restart_services
