## Name or list of names in case you want to create several apps with the same configuration
names: hdfs_sample
app_type: hadoop_app

## Resource configuration to load into State Database
cpu_max: 200
cpu_min: 200
mem_max: 4096
mem_min: 2048
cpu_boundary: 10
cpu_boundary_type: "percentage_of_max"
mem_boundary: 1
mem_boundary_type: "percentage_of_max"

## Only used if disk_scaling set to yes
disk_read_max: 400
disk_write_max: 400
disk_read_min: 10
disk_write_min: 10
disk_read_boundary: 10
disk_write_boundary: 10
disk_read_boundary_type: "percentage_of_max"
disk_write_boundary_type: "percentage_of_max"

## The indicated files should be in the same directory as this configuration file
start_script: start.sh
stop_script: stop.sh
app_jar: app_jar.jar
