- name: Setup power sensor
  block:
    - name: Create power sensor installation directory
      file:
        path: "{{ power_sensor_path }}/image"
        state: directory
        owner: "{{ user_info.user_name }}"

    - name: Create power sensor configuration directory
      file:
        path: "{{ power_sensor_path }}/config"
        state: directory
        owner: "{{ user_info.user_name }}"

    - name: Create sensor reporting directory
      file:
        path: "{{ sensor_reporting_path }}"
        state: directory
        owner: "{{ user_info.user_name }}"
  vars:
    - power_sensor: "{{ 'selfwatts_controller' if power_meter == 'selfwatts' else 'hwpc_sensor' }}"
    - power_sensor_path: "{{ installation_path }}/{{ power_sensor }}"
