- name: Setup power meter
  block:
    - name: Create power meter installation directory
      file:
        path: "{{ power_meter_path }}/image"
        state: directory
        owner: "{{ user_info.user_name }}"

    - name: Create power meter configuration directory
      file:
        path: "{{ power_meter_path }}/config"
        state: directory
        owner: "{{ user_info.user_name }}"
  vars:
    - v_power_meter: "{{ 'smartwatts' if power_meter == 'rapl' else power_meter }}"
    - power_meter_path: "{{ installation_path }}/{{ v_power_meter }}"
