- name: get the username running the deploy
  become: no
  local_action: command whoami
  register: username_on_the_host

- name: Create SelfWatts installation directory
  file:
    path: "{{ selfwatts_path }}/image"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"

- name: Create SelftWatts configuration directory
  file:
    path: "{{ selfwatts_path }}/config"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"