- import_tasks: "{{ util_tasks }}/get_tmux_sessions.yml"

- name: Copy BDWatchdog's source code to node
  synchronize:
    src: "{{ externals_dir }}/BDWatchdog/"
    dest: "{{ bdwatchdog_source_path }}"

- name: Copy disk_atop code to node
  synchronize:
    src: "{{ services_dir }}/disk_atop"
    dest: "{{ installation_path }}/"

- name: Template start script
  template:
    src: "{{ services_dir }}/disk_atop/start.sh"
    dest: "{{ installation_path }}/disk_atop/start.sh"

- name: Start disk atop service
  when: "'disk_atop' not in tmux_sessions"
  shell: bash start_tmux.sh
  args:
    chdir: "{{ installation_path }}/disk_atop"
    executable: /bin/bash
