
- name: Start SelfWatts inside an apptainer/singularity container
  block:
    - name: Check if SelfWatts image already exists
      stat:
        path: "{{ selfwatts_path }}/image/{{ image_file }}"
        get_checksum: false
        get_mime: false
        get_attributes: false
      register: stat_output

    - name: Copy SelfWatts container definition file
      when: not stat_output.stat.exists
      template:
        src: "templates/power_budgeting/monitoring/power_meter/{{ definition_file }}"
        dest: "{{ selfwatts_path }}/image/{{ definition_file }}"

    - name: Copy SelfWatts configuration files
      when: not stat_output.stat.exists
      template:
        src: "templates/power_budgeting/monitoring/power_meter/config/{{ item }}"
        dest: "{{ selfwatts_path }}/config/{{ item }}"
      with_items:
        - context-selfwatts.py
        - handler-selfwatts.py
        - opentsdb-selfwatts.py
        - powerapi-0.9.3-setup.cfg

    - name: Build image
      when: not stat_output.stat.exists
      shell: "{{ singularity_command_alias }} build image/{{ image_file }} image/{{ definition_file }}"
      args:
        chdir: "{{ selfwatts_path }}"
        executable: /bin/bash
        creates: "image/{{ image_file }}"

    - name: Check containers status
      shell: "{{ singularity_command_alias }} instance list -j"
      register: apptainer_list_output
      args:
        executable: /bin/bash

    - name: Start SelfWatts apptainer container
      shell: "{{ singularity_command_alias }} instance start -C image/{{ image_file }} {{ container_name }}"
      when: "container_name not in apptainer_list_output.stdout"
      args:
        chdir: "{{ selfwatts_path }}"
        executable: /bin/bash

  when: "container_engine == 'apptainer'"
  vars:
    - definition_file: "selfwatts.def"
    - image_file: "selfwatts.sif"
    - container_name: "selfwatts"

- name: Start SelfWatts inside a lxc container
  debug:
    msg: 'SelfWatts inside a lxc container not yet supported'
  when: "container_engine == 'lxc'"