- name: Starting Services - Web Interface
  shell: "bash start_tmux.sh {{ web_interface_port }}"
  when: "'web_interface' not in tmux_sessions"
  args:
    chdir: "{{ web_interface_path }}"
    executable: /bin/bash

- name: Starting Services - Redis server
  shell: "bash start_tmux.sh {{ installation_path }}"
  when: "'redis_server' not in tmux_sessions"
  args:
    chdir: "services/redis_server"
    executable: /bin/bash

- name: Starting other Services
  shell: "bash start_tmux.sh"
  when: "item not in tmux_sessions"
  args:
    chdir: "services/{{ item }}"
    executable: /bin/bash
  with_items:
    - celery
    - rebooter
