- name: Starting Services - Web Interface
  shell: "bash start_tmux.sh {{ web_interface_port }}"
  when: "'web_interface' not in tmux_sessions"
  args:
    chdir: "{{ services_dir }}/serverless_containers_web"
    executable: /bin/bash

- name: Starting Services - Redis server
  shell: "bash start_tmux.sh {{ installation_path }}"
  when: "'redis_server' not in tmux_sessions"
  args:
    chdir: "{{ services_dir }}/redis_server"
    executable: /bin/bash

- name: Starting other Services
  shell: "bash start_tmux.sh"
  when: "item not in tmux_sessions"
  args:
    chdir: "{{ services_dir }}/{{ item }}"
    executable: /bin/bash
  with_items:
    - celery
    - config_updater

 ## Always launch 'rebooter' last to avoid conflicts with service startup
- name: Starting Services - Rebooter
  shell: "bash start_tmux.sh"
  when: "'rebooter' not in tmux_sessions and enable_rebooter"
  args:
    chdir: "{{ services_dir }}/rebooter"
    executable: /bin/bash