# Manage scaling services
- name: Manage scaling services
  hosts: localhost
  become: no
  any_errors_fatal: yes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  environment:
    INSTALLATION_PATH: "{{ installation_path }}"
    SERVERLESS_PATH: "{{ serverless_containers_path }}"
    PYTHONPATH: "{{ bdwatchdog_path }}:{{ serverless_containers_path }}"

  tasks:
    ## Disable scaling services
    ### This unified approach makes it easier to expand the task to disable specific services, rather than creating separate tasks
    ### The inner loop of the shell command, rather than an Ansible loop, should run slightly faster
    - name: Disabling services that generate scaling requests
      shell: |
        {% for item in services_to_disable | select | list %}
          bash scripts/orchestrator/{{ item }}/deactivate.sh &&
        {% endfor %}true
      args:
        chdir: "{{ serverless_containers_path }}"
        executable: /bin/bash
      vars:
        tags_active: "{{ ansible_run_tags | list }}"
        disable_scaler: "{{ tags_active | intersect(['disable_scaler', 'disable_scaling_services']) | length > 0 }}"
        disable_scaling: "{{ tags_active | intersect(['disable_scaling_services']) | length > 0 }}"
        services_to_disable:
          - "{{ 'Scaler' if disable_scaler else '' }}"
          - "{{ 'Rebalancer' if disable_scaling else '' }}"
          - "{{ 'Guardian' if not power_budgeting and disable_scaling else '' }}"
          - "{{ 'EnergyController' if power_budgeting and disable_scaling else '' }}"
      tags: never, disable_scaler, disable_scaling_services

    ## Re-enable services
    - name: Re-enabling services that generate scaling requests
      shell: |
        {% for item in services_to_enable | select | list %}
          bash scripts/orchestrator/{{ item }}/activate.sh &&
        {% endfor %}true
      args:
        chdir: "{{ serverless_containers_path }}"
        executable: /bin/bash
      vars:
        tags_active: "{{ ansible_run_tags | list }}"
        enable_scaler: "{{ tags_active | intersect(['enable_scaler', 'enable_scaling_services']) | length > 0 }}"
        enable_scaling: "{{ tags_active | intersect(['enable_scaling_services']) | length > 0 }}"
        services_to_enable:
          - "{{ 'Scaler' if enable_scaler else '' }}"
          - "{{ 'Rebalancer' if enable_scaling else '' }}"
          - "{{ 'Guardian' if not power_budgeting and enable_scaling else '' }}"
          - "{{ 'EnergyController' if power_budgeting and enable_scaling else '' }}"
      tags: never, enable_scaler, enable_scaling_services